export const RUNTIME_TUNING = Object.freeze({
  CHAT_LOG_MAX_ENTRIES: 36,
  CHAT_ECHO_DEDUP_MS: 6000,
  CHAT_SYSTEM_DEDUP_MS: 4000,
  CLOUD_MIN_AREA: 800,
  HUD_FPS_SAMPLE_SECONDS: 0.5,
  HUD_REFRESH_INTERVAL_SECONDS: 0.15
});
